docs/07_연산자/박준서.md

7장 연산자 - 박준서

---

docs/08_제어문/박준서.md

8장 제어문 - 박준서

---

docs/19_프로토타입/강인영.md

19장 프로토타입 - 강인영

---

docs/20_strict mode/강인영.md

20장 strict mode - 강인영

---

docs/21_빌트인 객체/강인영.md

21장 빌트인 객체 - 강인영

---

docs/22_this/강인영.md

22장 this - 강인영

---

docs/24_클로저/강인영.md

24장 클로저 - 강인영

---

docs/25_클래스/강인영.md

25장 클래스 - 강인영

---

docs/20_strict mode/이보리.md

이제 확인해보니까 리드미에는 제가 DAY5에 완료했다고 되어있네요.
이 때 몸이 안좋아서 PR은 못날리고 따로 정리만 해두었습니다.
확인 부탁드립니다🙂

20장 strict mode - 이보리

---

docs/28_Number/강인영.md

28장 Number - 강인영

---

docs/37_Set과 Map/강인영.md

37장 Set과 Map - 강인영

---

docs/39_DOM/강인영.md

39장 DOM - 강인영

---

docs/07_연산자/강철원B.md

7-2장 연산자 - 강철원

---

docs/08_제어문/이나린.md

8장 제어문 - 이나린

---

docs/09_타입 변환과 단축 평가/이나린.md

Day 9
- 9장 타입 변환과 단축 평가
- 9.1 ~ 9.2 (Day 8) 
- 9.3 ~ 9.4 (Day 9)

9-2장 타입 변환과 단축 평가 - 이나린

---

docs/09_타입 변환과 단축 평가/김경주.md

9-2장 타입 변환과 단축 평가 - 김경주

---

docs/10_객체 리터럴/이나린.md

Day 11
- 10장 객체 리터럴
- 10.1 ~ 10.5 (Day10)
- 10.6 ~ 10.9 (Day11)

10-2장 객체 리터럴 - 이나린

---

docs/13_스코프/이나린.md

Day 16
- 13장 스코프
- 13.1 ~ 13.2 (Day16)

13-1장 스코프 - 이나린

---

docs/15_let, const 키워드와 블록 레벨 스코프/김경주.md

15장 let, const 키워드와 블록 레벨 스코프 - 김경주

---

docs/16_프로퍼티 어트리뷰트/이나린.md

Day 20
- 16장 프로퍼티 어트리뷰트
- 16.1 ~ 16.3 (Day 20)

16-1장 프로퍼티 어트리뷰트 - 이나린

---

docs/16_프로퍼티 어트리뷰트/김은지.md

16-2장 프로퍼티 어트리뷰트 - 김은지

---

docs/16_프로퍼티 어트리뷰트/이나린.md

Day 21
- 16장 프로퍼티 어트리뷰트
- 16.1 ~ 16.3 (Day 20)
- 16.4 ~ 16.5 (Day 21)

16-2장 프로퍼티 어트리뷰트 - 이나린

---

docs/16_프로퍼티 어트리뷰트/김경주.md

16-2장 프로퍼티 어트리뷰트 - 김경주

---

docs/17_생성자 함수에 의한 객체 생성/이나린.md

Day 22
- 17장 생성자 함수에 의한 객체 생성
- 17.1 ~ 17.2.3 (Day 22)

17-1장 생성자 함수에 의한 객체 생성 - 이나린

---

docs/17_생성자 함수에 의한 객체 생성/김경주.md

17-2장 생성자 함수에 의한 객체 생성 - 김경주

---

docs/17_생성자 함수에 의한 객체 생성/강철원B.md

17-2장 생성자 함수에 의한 객체 생성 - 강철원

---

docs/18_함수와 일급 객체/이나린.md

Day 24
- 18장 함수와 일급 객체
- 18.1 ~ 18.2

18장 함수와 일급 객체 - 이나린

---

docs/19_프로토타입/이나린.md

Day25
- 19장 프로토타입
- 19.1 ~ 19.2

19-1장 프로토타입 - 이나린

---

docs/19_프로토타입/이나린.md

Day26
- 19장 프로토타입
- 19.1 ~ 19.2 (Day25)
- 19.3 (Day26)

19-2장 프로토타입 - 이나린

---

docs/19_프로토타입/강철원B.md

19-3장 프로토타입 - 강철원

---

docs/19_프로토타입/이나린.md

Day27
- 19장 프로토타입
- 19.1 ~ 19.2 (Day 25)
- 19.3 (Day 26)
- 19.4 ~ 19.6 (Day 27)

19-3장 프로토타입 - 이나린

---

docs/19_프로토타입/이나린.md

Day 28
- 19장 프로토타입
- 19.1 ~ 19.2 (Day 25)
- 19.3 (Day 26)
- 19.4 ~ 19.6 (Day 27)
- 19.7 ~ 19.9 (Day 28)

19-4장 프로토타입 - 이나린

---

docs/19_프로토타입/고세종.md

19-5장 프로토타입 - 고세종

---

docs/19_프로토타입/이나린.md

Day 29
- 19장 프로토타입
- 19.1 ~ 19.2 (Day 25)
- 19.3 (Day 26)
- 19.4 ~ 19.6 (Day 27)
- 19.7 ~ 19.9 (Day 28)
- 19.19 ~ 19.11 (Day 29)

19-5장 프로토타입 - 이나린

---

docs/19_프로토타입/장서윤.md

제출 못한 부분(19.12~14) 제출합니다! 
항상 머지하시느라 고생 많으십니다🙇‍♂️

19-6장 프로토타입 - 장서윤

---

docs/20_strict mode/이나린.md

Day 1
- 20장 strict mode
- 20.1 ~ 20.6

20장 strict mode - 이나린

---

docs/20_strict mode/김유나.md

북스터디 첫 참여합니다! 
잘못한 부분 있으면 알려주세요☺️
20. strict mode

20장 strict mode - 김유나

---

docs/20_strict mode/김경주.md

20장 strict mode - 김경주

---

docs/21_빌트인 객체/김유나.md

21-1장 빌트인 객체 - 김유나

---

docs/21_빌트인 객체/이나린.md

Day 2
- 21장 빌트인 객체
- 21.1 ~ 21.3 (Day 2)

21-1장 빌트인 객체 - 이나린

---

docs/21_빌트인 객체/이나린.md

Day 3
- 21장 빌트인 객체
- 21.1 ~ 21.2 (Day 2)
- 21.3 (Day 3)

21-2장 빌트인 객체 - 이나린

---

docs/21_빌트인 객체/김경주.md

21-2장 빌트인 객체 - 김경주

---

docs/22_this/김유나.md

22장 this - 김유나

---

docs/22_this/고세종.md

21장 this - 고세종

---

docs/22_this/이나린.md

docs : Day 4
- 22장 this
- 22.1 ~ 22.2

22장 this - 이나린

---

docs/22_this/김경주.md

22장 this - 김경주

---

README.md

docs: 체크리스트 업데이트 (시즌2)

---

README.md

docs: 체크리스트 업데이트 (시즌 2)

---

docs/23_실행 컨텍스트/김은지.md

```js
let lamp = false;
function goTo2F() {
let lamp = true;
console.log(lamp);
}
goTo2F():
```
1. 전역 실행 컨텍스트가 실행 중일 때 전역 렉시컬 환경에서 식별자 `lamp`, `goTo2F`를 검색한다.
2. 모든 식별자를 전역 실행 컨텍스트의 렉시컬 환경에서 검색할 수 있으므로 검색된 식별자에 값을 바인딩 한다.
3. goTo2F 함수 실행 컨텍스트가 실행 중일 때 goTo2F 함수 렉시컬 환경에서 식별자 `lamp`를 검색하고 값이 할당된다.
4. console.log에서 메서드에 전달할 `lamp` 식별자를 goTo2F 함수 렉시컬 환경에서 검색하여 평가되면 console.log 메서드에 전달하여 호출한다.
```js
const x = 1;
function foo() {
const y = 2;
function bar() {
const z = 3;
console.log(x + y + z);
}
bar();
}
foo();
```
```
<보기>
-bar 함수 코드의 평가와 실행
-전역 코드로 복귀
-foo 함수 코드로 복귀
-foo함수 코드의 평가와 실행
-전역 코드의 평가와 실행
```
```
1. 전역 코드의 평가와 실행
2. foo함수 코드의 평가와 실행
3. bar 함수 코드의 평가와 실행
4. foo 함수 코드로 복귀
5. 전역 코드로 복귀
```
```js
let x = 10;
if (true) {
let x = 1;
console.log(x); // 1️⃣
}
console.log(x); // 2️⃣
``` …

23-3장 실행 컨텍스트 - 김은지

---

README.md

docs: 체크리스트 업데이트 (시즌 2)

---

docs/24_클로저/심채윤.md

```js
const increase = (function () {
let num = 0;
return function () {
return ++num;
}
}());
console.log(increase()); // ?
console.log(increase()); // ?
```
```
1️⃣ 1
2️⃣ 2
```
```
클로저는 함수 생성 시 자신이 만들어진 스코프에 있는 변수를 기억한다. 따라서 함수가 외부 함수의 외부에서 호출되더라도, 클로저는 여전히 자신을 감싸고 있는 외부 함수의 지역변수에 접근할 수 있다.
```
객체의 상태를 나타내는 프로퍼티와 프로퍼티를 참조하고 조작할 수 있는 동작인 메서드를 하나로 묶는 것을 [ ] 라고 한다.
이때, [ ] 은 객체의 특정 프로퍼티나 메서드를 감출 목적으로 사용하기도 하는데 이를 [ ] 라고 한다.
```
1️⃣ 캡슐화
2️⃣ 정보 은닉
```
<br /><br /><br />
---
Quiz by #1004

24-2장 클로저 - 심채윤

---

docs/25_클래스/이나린.md

Day 10
- 25장 클래스
- 25.1 ~ 25.5

25-1장 클래스 - 이나린

---

docs/25_클래스/강철원B.md

25-1장 클래스 - 강철원

---

README.md

docs: 체크리스트 업데이트 (시즌2)

---

docs/25_클래스/심채윤.md

```
정적메서드는 클래스로 호출되며 인스턴스 프로퍼티를 참조할 수 있다.
반면에 프로토타입 메서드는 인스턴스로 호출하며 인스턴스 프로퍼티를 참조할 수 없다.
```
```
클래스 선언문은 호이스팅이 발생하지 않는것처럼 보이지만,
일시적 사각지대(TDZ) 빠져 참조할 수 없는 상태로 존재한다.
클래스의 선언은 먼저 메모리에 등록되어 이후 실제 코드에 도달했을때 초기화가 이루어진다.
```
```
❌ 파스칼 케이스를 사용하는 것이 일반적이나, 사용하지 않아도 에러가 발생하지 않는다.
✅ 일시적 사각지대에 빠져 선언 전에 참조할수 없다.
✅ 클래스에서 정의한 메서드는 내부 메서드 [[Contruct]]를 갖지 않는 non-contructor이다.
❌ constructor 내부에서 정의되지 않았기 때문에 인스턴스 프로퍼티 메서드가 될 수 없다.
```
( 코드는 에러를 무시하고 전부 실행된다고 가정가정하고 실행 환경은 node.js v18입니다.)
```js
class Base {
constructor(a, b) {
this.a = a
this.b = b
age = 24      // (2)
}
}
class Derived extends Base {
constructor(a, b, c, d) { …
```

25-3장 클래스 - 심채윤

---

docs/25_클래스/장서윤.md

- 둘다 클래스 내부 몸체에 정의하며, 정적 메서드의 경우 `static` 키워드를 붙혀야 한다.
- 정적 메서드와 프로토타입 메서드는 자신이 속해 있는 프로토타입 체인이 다르다.
- 정적 메서드는 **클래스**로 호출 <-> 프로토타입 메서드는 **인스턴스**로 호출한다. 
-  정적 메서드는 인스턴스 프로퍼티를 참조할 수 없지만 프로토타입 메서드는 인스턴스 프로퍼티를 참조할 수 있다.
- 클래스는 `var` 키워드로 선언한 변수가 아닌 `let`, `const` 로 선언한 변수처럼 호이스팅된다. 이에 일시적 사각지대(23장 참고)에 빠져, 호이스팅이 발생하지 않는 것처럼 동작한다.
1. 클래스 이름은 무조건 파스칼 케이스로 지어야 한다. ❌
일반적으로 파스칼 케이스를 사용하며, 사용하지 않더라도 에러가 발생하진 않는다.
2. 클래스는 선언 이전에 참조할 수 없다. ⭕️
호이스팅으로 일시적 사각지대에 빠지게 되므로, 선언 이전에 참조할 수 없다.
3. 클래스에서 정의한 메서드는 모두 non-constructor다. ⭕️
모두 내부 메서드 [[Construct]]를 갖지 않는 non-constructor다.
4. 클래스에서 getter, setter 메서드를 정의하면 인스턴스의 프로퍼티 메서드가 된다. ❌
접근자 프로퍼티(getter, setter)를 사용할 경우, 프로토타입의 프로퍼티가 된다!
```js
class Base {
constructor(a, b) {
this.a = a
this.b = b
age = 24      // (2)
}
}
class …
```

25-3장 클래스 - 장서윤

---

docs/25_클래스/강철원B.md

- 정적메서드와 프로토타입 메서드는 자신이 속해있는 프로토타입 체인이 다르다.
- 정적 메서드는 클래스로 호출하고 프로토타입 메서드는 인스턴스로 호출한다.
- 정적 메서드는 인스턴스 프로퍼티를 참조할 수 없지만 프로토타입 메서드는 인스턴스 프로퍼티를 참조할 수 있다.
❌ 파스칼 케이스로 짓지 않아도 되긴 하지만, 일반적으로 파스칼 케이스를 사용합니다.
O TDZ에 빠집니다.
O, 모든 메서드는 내부 메서드 [[Construct]]를 갖지 않는 non-constructor다.
❌ 프로토타입 메서드가 된다. 
( 코드는 에러를 무시하고 전부 실행된다고 가정가정하고 실행 환경은 node.js v18입니다.)
```js
class Base {
constructor(a, b) {
this.a = a
this.b = b
age = 24      // (2)
}
}
class Derived extends Base {
constructor(a, b, c, d) {
this.c = c        // (3)
super(a, b)
this.d = d       // (4)
}
sayName() {
console.log(this.name)
}
}
const derived = new Derived(1, 2, 3) …
```

25-3장 클래스 - 강철원

---

docs/25_클래스/김다은.md

- **선언 방법**: 정적 메서드는 static 키워드를 붙여 선언해야 한다. 프로토타입 메서드는 키워드 없이 선언할 수 있다. 
- **호출 방식**: 정적 메서드는 인스턴스를 생성하지 않고 클래스 이름으로 직접 호출된다. 프로토타입 메서드는 인스턴스를 통해 호출할 수 있다.
- **사용 목적**: 정적 메서드는 인스턴스와 독립적인 기능을 제공하거나, 해당 클래스에 고유한 기능(헬퍼 함수, 설정 함수)을 제공하는 데 사용된다. 반면 프로토타입 메서드는 인스턴스의 데이터에 접근하거나 조작하는 기능을 제공하는 데 주로 사용된다.
- **this 참조**: 정적 메서드의 this는 클래스 자체를 가리킨다. 따라서 정적 메서드 내에서는 클래스의 정적 속성에 접근할 수 있다. 프로토타입 메서드는 해당 메서드를 호출한 인스턴스를 가리킨다. 따라서 인스턴스의 속성과 메서드에 접근할 수 있다.
<br/>
클래스 선언문으로 정의한 클래스는 런터임 이전에 먼저 평가되어 함수 객체를 생성한다. 평과 결과는 constructor 함수와 프로토타입 쌍이다. 
다만 let, const 로 선언한 변수처럼 일시적 사각지대에 빠져 호이스팅이 발생하지 않는 것 처럼 동작한다.
<br/>
1. X, 권장할 뿐 강제성은 없다.
2. O, let과 const처럼 일시적 …

25-3장 클래스 - 김다은

---

docs/25_클래스/문소희.md

> 1. 정적 메서드와 프로토타입 메서드는 자신이 속해 있는 프로토타입 체인이 다르다.
> 2. 정적 메서드는 클래스로 호출하고 프로토타입 메서드는 인스턴스로 호출한다.
> 3. 정적 메서드는 인스턴스 프로퍼티를 참조할 수 없고, 프로토타입 메서드는 인스턴스 프로퍼티를 참조할 수 있다.
> let, const 키워드로 선언한 변수처럼 호이스팅된다. 따라서 클래스 선언문 이전에 일시적 사각지대(TDZ)에 빠지기 때문에 호이스팅이 발생하지 않는 것처럼 동작한다.
> 1. X 파스칼 케이스를 사용하는 것이 일반적이지만 필수는 아니다.
> 2. O 호이스팅이 이루어지면서 일시적 사각지대(TDZ)에 빠지기 때문에 클래스는 선언 이전에 참조가 불가능하다. 
> 3. O 내부 메서드 [[Construct]]를 가지지 않는 non-constructor이다. 따라서 new 연산자와 함께 호출할 수 없다.
> 4. X 클래스의 메서드는 기본적으로 프로토타입 메서드가 되며, 클래스의 접근자 프로퍼티 또한 인스턴스 프로퍼티가 아닌 프로토타입의 프로퍼티가 된다.
( 코드는 에러를 무시하고 전부 실행된다고 가정가정하고 실행 환경은 node.js v18입니다.)
```js
class Base {
constructor(a, …
```

25-3장 클래스 - 문소희

---

docs/25_클래스/이나린.md

- 정적 메서드는 클래스로 호출, 프로토타입 메서드는 인스턴스로 호출한다.
- 정적 메서드는 프로토타입 메서드와 달리 인스턴스 프로퍼티를 참조할 수 없다.
- 정적 메서드와 프로토타입 메서드는 자신이 속해 있는 프로토타입 체인이 다르다.
마치 호이스팅이 발생하지 않는 것처럼 동작한다. 하지만 클래스 선언문도 변수를 선언할 때와 같이 호이스팅이 발생한다.
1. X - 파스칼 케이스가 일반적인 것이지, 반드시 파스칼 케이스일 필요는 없다.
2. O - 클래스는 클래스 정의 이전에 참조할 수 없다. 참조 시 ReferenceError가 발생한다. 이는 선언문 이전에 TDZ에 빠지기 때문이다.
3. O - non-constructor이기 때문에 new 연사자와 함께 호출할 수 없다.
4. X - 클래스의 메서드는 기본적으로 프로토타입 메서드가 된다.
( 코드는 에러를 무시하고 전부 실행된다고 가정가정하고 실행 환경은 node.js v18입니다.)
```javascript
class Base {
constructor(a, b) {
this.a = a
this.b = b
age = 24      // (2)
}
}
class Derived extends Base {
constructor(a, b, c, d) …
```

25-3장 클래스 - 이나린

---

docs/26_ES6 함수의 추가 기능/강철원B.md

 26-2장 ES6 함수의 추가 기능 - 강철원

---

docs/27_배열/이나린.md

27-2장 배열 - 이나린

---

docs/27_배열/심채윤.md

delete 연산자를 사용하면 요소가 실제로 제거되는 것이 아닌 비어있는 요소, 즉 undefined로 남게 된다. 원래의 배열은 비어있는 요소를 가지고 있는 희소 배열이 되어 연산 및 메서드 사용 시 예상하지 못한 오류를 야기할 수 있다.
```js
console.log([1, , 3].includes(undefined)); 
```
```
true
```
```js
const arrayLike = {
length: 3,
0: 2,
1: 3,
2: 4,
3: 1,
};
```
arrayLike 객체는 0부터 시작하는 정수형 인덱스를 가지고, 'length' 프로퍼티가 존재하기 때문에 유사 배열 객체로 볼 수 있다. 따라서 아래와 같이 includes 메서드를 사용할 수 있다.
```js
Array.from(arrayLike).includes()
```
<br />
---
Quiz #1095

27-3장 배열 - 심채윤

---

docs/27_배열/강철원B.md

`delete`로 삭제하면 배열은 희소배열이 되며 `length`프로퍼티 값이 변경되지 않기 때문입니다. (p507)
그래서 희소배열을 만들지 않으면서 배열의 특정 요소를 완전히 삭제하는 `splice`메서드를 사용하는 것이 좋습니다.
---
```js
console.log([1, , 3].includes(undefined)); 
```
[희소 배열에서 `undefined`를 검색하면 `ture`를 얻을 수 있습니다.](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/includes#%ED%9D%AC%EC%86%8C_%EB%B0%B0%EC%97%B4%EC%97%90%EC%84%9C_includes_%EC%82%AC%EC%9A%A9%ED%95%98%EA%B8%B0)
---
```js
const arrayLike = {
length: 3,
0: 2,
1: 3,
2: 4,
3: 1,
};
```
```js
console.log(Array.prototype.includes.call(arrayLike, 2)); // true
console.log(Array.prototype.includes.call(arrayLike, 1)); // false
```
[참고](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/includes#%EB%B0%B0%EC%97%B4%EC%9D%B4_%EC%95%84%EB%8B%8C_%EA%B0% …

27-3장 배열 - 강철원

---

docs/27_배열/이나린.md

희소 배열을 만들기 때문이다.
희소 배열 없이 완전히 삭제하려면 splice 메서드를 사용한다.
```javascript
console.log([1, , 3].includes(undefined)); 
```
true
```javascript
const arrayLike = {
length: 3,
0: 2,
1: 3,
2: 4,
3: 1,
};
```
```javascript
Array.from(arrayLike).includes();
```
#1095

27-3장 배열 - 이나린

---

docs/27_배열/문소희.md

> delete 연산자는 객체의 프로퍼티를 삭제할 수 있지만, 희소 배열을 만들기 때문에 사용하지 않는 것이 좋다. 희소 배열을 만들지 않으면서 배열의 특정 요소를 삭제하고 싶은 경우에는 `Array.prototype.splice`를 사용한다.
```js
console.log([1, , 3].includes(undefined)); 
```
```js
true
```
```js
const arrayLike = {
length: 3,
0: 2,
1: 3,
2: 4,
3: 1,
};
```
> arrayLike는 유사 배열 객체이기 때문에 Array.from 메서드를 사용해 배열로 변환시킨 후 `includes()`를 사용한다.
```js
Array.from(arrayLike).includes();
```
#1095

27-3장 배열 - 문소희

---

docs/28_Number/최주용.md

#1114 
Q1) 인수로 전달받은 소수점 자릿수 혹은 전체 자릿수까지 유효하도록 반올림하는 메서드는 각각 무엇인가요 ?
-> Number.prototype.toFixed, Number.prototype.toPrecision

28장 Number - 최주용

---

docs/28_Number/백세희.md

```js
//  Number.isNaN은 인수를 숫자로 암묵적 타입 변환하지 않는다.
Number.isNaN(undefined);  //  a
//  isNaN은 인수를 숫자로 암묵적 타입 변환된다. undefined는 NaN으로 암묵적 타입 변환된다. 
isNaN(undefined);  //  b
```
#1114

28장 Number - 백세희

---

docs/28_Number/이나린.md

빌트인 전역 함수는 전달받은 인수를 숫자로 암묵적 타입 변환 후 검사를 수행하고,
Number 메서드는 암묵적 타입 변환을 하지 않는다.
#1114

28장 Number - 이나린

---

docs/28_Number/김다은.md

1. isNaN('123')
2. Number.isNaN('123')
3. isNaN('NaN')
4. Number.isNaN('NaN')
5. isNaN(undefined)
6. Number.isNaN(undefined)
**3, 5**
isNaN은 인자로 들어온 값의 타입 변환을 시도하는 반면 Number.isNaN은 타입 변환을 시도하지 않는다. 따라서 Number.isNaN은 인자가 숫자 타입인지와 그 값이 NaN인지를 모두 검사하는 더 엄격한 메서드라고 볼 수 있다.
- 3번의 경우 문자열 `'NaN'`을 타입 변환하면 NaN이 되기 때문에 `isNaN(NaN)`과 같아진다. 따라서 `isNaN('NaN')`은 true가 된다. 반면 4번의 `Number.isNaN('NaN')`의 경우 인자가 문자열로 숫자 타입이 아니기 때문에 false가 반환된다.
- 5번의 경우 undefined은 타입 변환 후 NaN이 되기 때문에 `isNaN(NaN)`과 같다. 따라서 `isNaN(undefined)`은 true가 된다. 반면 6번의 `Number.isNaN`의 경우 undefined는 숫자 타입도 아닐 뿐더러 NaN도 아니기 때문에 false가 반환된다.
<br/>

28장 Number - 김다은

---

docs/28_Number/김은지.md

- 전역 함수 `isFinite()`는 전달받은 인수를 숫자로 암묵적 타입 변환.
- 반면 `Number.isFinite()` 메서드는 전달받은 인수를 숫자로 암묵적 타입 변환하지 않음. 따라서 인수가 숫자가 아닐 경우 언제나 `false`를 반환.
- #1114

28장 Number - 김은지

---

docs/28_Number/강철원B.md

Q1. isNaN() vs Number.isNaN()의 차이를 설명하세요
A1
```js
isNaN('hello world'); // true
Number.isNaN('hello world'); // false
```
- `isNaN()`
- 인자를 숫자로 변환하는 과정을 겨쳐 판별합니다.
- `Number.isNaN()`
- 인자로 들어온 값이 `NaN`이어야만 `true`를 리턴합니다.   
- #1114

28장 Number - 강철원

---

docs/28_Number/장서윤.md

- new 연산자 함께 호출 -> **Number 인스턴스를 생성**하여. [[NumberData]] 내부 슬롯에 인수를 할당한다(기본은 0 할당)
-  new 연산자 없이 호출 -> 인스턴스가 아닌 숫자를 반환한다. 
#1114

28장 Number - 장서윤

---

docs/33_7번째 데이터 타입 Symbol/이나린.md

Day 1
- 33장 7번째 데이터 타입 Symbol
- 33.1 ~ 33.3

33-1장 7번째 데이터 타입 Symbol - 이나린

---

docs/33_7번째 데이터 타입 Symbol/강철원B.md

 33-1장 7번째 데이터 타입 Symbol - 강철원

---

README.md

docs: 체크리스트 업데이트

---

docs/34_이터러블/고세종.md

34-1장 이터러블 - 고세종

---

docs/34_이터러블/이나린.md

Day 3
- 34장 이터러블
- 34.1 ~ 34.3

34-1장 이터러블 - 이나린

---

docs/34_이터러블/이나린.md

Day 4
- 34장 이터러블
- 34.4. ~ 34.6

34-2장 이터러블 - 이나린

---

docs/37_Set과 Map/이나린.md

37-1장 Set과 Map - 이나린

---

docs/37_Set과 Map/고세종.md

37-1장 Set과 Map - 고세종

---

docs/37_Set과 Map/고세종.md

37-2장 Set과 Map - 고세종

---

docs/37_Set과 Map/이나린.md

37-2장 Set과 Map - 이나린

---

docs/39_DOM/강철원B.md

39-2장 DOM - 강철원

---

docs/39_DOM/강철원B.md

39-3장 DOM - 강철원

---

docs/39_DOM/이나린.md

Day 12
- 39장 DOM
- 39.2.4~39.2.6

39-3장 DOM - 이나린

---

docs/39_DOM/이나린.md

39-4장 DOM - 이나린

---

docs/39_DOM/고세종.md

39-4장 DOM - 고세종

---

docs/39_DOM/이나린.md

Day 14
- 39장 DOM
- 39.4 ~ 39.6.2

39-5장 DOM - 이나린

---

docs/39_DOM/고세종.md

39-6장 DOM - 고세종

---

docs/39_DOM/이나린.md

Day 15
- 39장 DOM
- 39.6.3 ~ 39.6.9

39-6장 DOM - 이나린

---

docs/39_DOM/고세종.md

39-7장 DOM - 고세종

---

docs/43_Ajax/이나린.md

43장 Ajax - 이나린

---

README.md

docs: 진도표 추가
